#!/bin/bash

declare -r threads='16'

ucurl() {
    curl -L -g -s --user-agent 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.15.2 Chrome/87.0.4280.144 Safari/537.36' -H 'Accept-Encoding: gzip, deflate' --compressed "$@"
}

declare -r arg0="$(basename "$0")"

usage() {
    printf '%s [dir] [URL]...\nArchive xvideos videos metadata in json to DIR\nUrls are taken from recursive spider starting from URL.\n' "$arg0"
}

get_page() {
    local -r rh="$(sha256sum <<< "$1")"
    local -r name="${rh%  *}"
    #local -r name3="${name:0:3}"
    [ -e "$name" ] && return #$name3/$name
    local -r t="$(ucurl "$1")"
    local jn="$(sed -n '/^<script>if(!window\.xv){window\.xv={};}window\.xv\.conf=/{s/^<script>if(!window\.xv){window\.xv={};}window.xv\.conf=//; s/;<\/script>$//; p;q}' <<< "$t")"
    local _tmp1
    {
    echo "$1" #link
    echo "$(jq -r '.dyn | "\(.id)\n\(.pagefilter)\n\(.vmdata.pub_comments)\n\(.video_title)"' <<< "$jn")" #id #pagefilter #comment_count #title
    jn="$(reliq 'script type="application/ld+json" | "%i\n"' <<< "$t")"
    echo "$(jq -r '"\(.uploadDate)\n\(.duration)"' <<< "$jn")" #date #duration
    echo "$(sed -n '/^[[:space:]]*html5player.setThumbUrl169(/{s/^.*('\''//; s/'\''.*$//;p;q}' <<< "$t")" #thumbnail
    echo "$(sed -n '/^[[:space:]]*html5player.setThumbSlideBig(/{s/^.*('\''//; s/'\''.*$//;p;q}' <<< "$t")" #mozaique

    reliq '
      . div .video-tags-list; a .uploader-tag href | "%(href)v\n" / sed "s#^/##",
      . div #v-views; strong .mobile-hide | "%i\n" / tr ",",
      . span .video-hd-mark | "%i\n",
      . span .rating-good-nbr | "%i\n",
      . span .rating-bad-nbr | "%i\n",
      . div .video-tags-list; a .is-keyword | "%i\t" / echo "" "\n",
      . div .video-tags-list; a .is-pornstar href | "%(href)v\t" / echo "" "\n"
    ' <<< "$t"
    } | jq -RnMc '
        .["link"]=input |
        .["id"]=input |
        .["pagefilter"]=input |
        .["comment_count"]=input |
        .["title"]=input |
        .["date"]=input |
        .["duration"]=input |
        .["thumbnail"]=input |
        .["mozaique"]=input |
        .["channel"]=input |
        .["views"]=input |
        .["quality"]=input |
        .["likes"]=input |
        .["dlikes"]=input |
        .["tags"]=(input | split("\t"))[:-1] |
        .["stars"]=(input | split("\t"))[:-1]' > "$name" #$name3/$name
    sed -n '/^<script>var video_related=/{s/^<script>var video_related=//; s/];window\..*/]/; p}' <<< "$t" | jq -r '"https://xvideos.com\(.[].u)"'
}

if [ "$#" -lt '2' ]
then
    usage >&2
    exit 1
fi

cd "$1" || exit 1
shift

t1="$(mktemp)"
trap 'rm "$t1"' EXIT
while [ "$#" -gt 0 ]
do
    echo "$1" >&2
    get_page "$1"
    shift
done > "$t1"

while :
do
    [ -s "$t1" ] || exit
    j="$(sort -u "$t1")"
    for i in $j
    do
        [ "$(jobs | wc -l)" -gt "$threads" ] && wait %%
        echo "$i" >&2
        get_page "$i" &
    done > "$t1"
    wait
done
